/**
 * Scraper
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ImagesResultImages {
    'head': string;
    'tall': string;
    'hero': string;
    'logo': string;
    'icon': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "head",
            "baseName": "head",
            "type": "string"
        },
        {
            "name": "tall",
            "baseName": "tall",
            "type": "string"
        },
        {
            "name": "hero",
            "baseName": "hero",
            "type": "string"
        },
        {
            "name": "logo",
            "baseName": "logo",
            "type": "string"
        },
        {
            "name": "icon",
            "baseName": "icon",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ImagesResultImages.attributeTypeMap;
    }
}

