name: Release
on:
	push:
		branches:
			- master
jobs:
	release:
		name: Release
		runs-on: ubuntu-latest
		steps:
			- name: Checkout
			  uses: actions/checkout@v2
			  with:
				fetch-depth: 0
			- name: Setup Node.js
			  uses: actions/setup-node@v2
			  with:
				node-version: lts/*
			- name: Install dependencies
			  run: yarn install --immutable --immutable-cache --check-cache
			- name: Test
			  run: yarn test
			- name: Build
			  run: yarn run build
			- name: Release
			  env:
				  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
				  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
			  run: yarn run semantic-release
			- name: Code Coverage
			  run: yarn run coverage
